### ISSUE TITLE
export() got an unexpected keyword argument '_retain_param_name'

### ISSUE THREAD

**Issue by froginfog** [sml2h3/dddd_trainer#14]
Traceback (most recent call last):
  File "D:\dddd_trainer-main\app.py", line 33, in <module>
    fire.Fire(App)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 681, in_CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "D:\dddd_trainer-main\app.py", line 28, in train
    trainer.start()
  File "D:\dddd_trainer-main\utils\train.py", line 152, in start
    self.net.export_onnx(self.net, dummy_input,
  File "D:\dddd_trainer-main\nets\__init__.py", line 216, in export_onnx
    torch.onnx.export(net, dummy_input, graph_path, export_params=True, verbose=False,
TypeError: export() got an unexpected keyword argument '_retain_param_name'

报了这个错误是怎么回事

**Comment by chldong** [comment]
Training Finished!Exporting Model...
Traceback (most recent call last):
  File "app.py", line 33, in <module>
    fire.Fire(App)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "app.py", line 28, in train
    trainer.start()
  File "/opt/dddd_trainer/utils/train.py", line 152, in start
    self.net.export_onnx(self.net, dummy_input,
  File "/opt/dddd_trainer/nets/__init__.py", line 216, in export_onnx
    torch.onnx.export(net, dummy_input, graph_path, export_params=True, verbose=False,
TypeError: export() got an unexpected keyword argument '_retain_param_name'

Ubuntu 训练完同样

**Comment by jaciyu** [comment]
Training Finished!Exporting Model...
Traceback (most recent call last):
  File "E:\dddd_trainer-main\app.py", line 33, in <module>
    fire.Fire(App)
  File "D:\Program Files\Python310\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\Program Files\Python310\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\Program Files\Python310\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "E:\dddd_trainer-main\app.py", line 28, in train
    trainer.start()
  File "E:\dddd_trainer-main\utils\train.py", line 152, in start
    self.net.export_onnx(self.net, dummy_input,
  File "E:\dddd_trainer-main\nets\__init__.py", line 216, in export_onnx
    torch.onnx.export(net, dummy_input, graph_path, export_params=True, verbose=False,
TypeError: export() got an unexpected keyword argument '_retain_param_name'
PS E:\dddd_trainer-main>
window 10 3090 cuda11.6 同样训练完毕导出的时候报异常

**Comment by yxnwh** [comment]
2022-07-28 11:25:37.843 | INFO     | utils.train:start:108 - [2022-07-28-11_25_37]      Epoch: 36       Step: 31800    LastLoss: 0.0010917907347902656                                                                                                      AvgLoss: 0.0009280425880569965   Lr: 0.007385691026454037
2022-07-28 11:25:39.978 | INFO     | utils.train:start:108 - [2022-07-28-11_25_39]      Epoch: 36       Step: 31900    LastLoss: 0.0008689984097145498                                                                                                      AvgLoss: 0.0008995186287211254   Lr: 0.007385691026454037
2022-07-28 11:25:42.212 | INFO     | utils.train:start:137 - [2022-07-28-11_25_42]      Epoch: 36       Step: 32000    LastLoss: 0.0010542419040575624                                                                                                      AvgLoss: 0.0008768078277353197   Lr: 0.007385691026454037        Acc: 0.90625
2022-07-28 11:25:44.384 | INFO     | utils.train:start:108 - [2022-07-28-11_25_44]      Epoch: 36       Step: 32100    LastLoss: 0.0006970251561142504                                                                                                      AvgLoss: 0.0008913403417682276   Lr: 0.0072379772059249555
2022-07-28 11:25:46.542 | INFO     | utils.train:start:108 - [2022-07-28-11_25_46]      Epoch: 36       Step: 32200    LastLoss: 0.0012068169889971614                                                                                                      AvgLoss: 0.0008795152555103414   Lr: 0.0072379772059249555
2022-07-28 11:25:48.683 | INFO     | utils.train:start:108 - [2022-07-28-11_25_48]      Epoch: 36       Step: 32300    LastLoss: 0.0005893478519283235                                                                                                      AvgLoss: 0.0008610051040886901   Lr: 0.0072379772059249555
2022-07-28 11:25:50.824 | INFO     | utils.train:start:108 - [2022-07-28-11_25_50]      Epoch: 36       Step: 32400    LastLoss: 0.0008560416754335165                                                                                                      AvgLoss: 0.0008518385927891359   Lr: 0.0072379772059249555
2022-07-28 11:25:52.967 | INFO     | utils.train:start:108 - [2022-07-28-11_25_52]      Epoch: 36       Step: 32500    LastLoss: 0.0007048668339848518                                                                                                      AvgLoss: 0.0008719124580966309   Lr: 0.0072379772059249555
2022-07-28 11:25:55.062 | INFO     | utils.train:start:108 - [2022-07-28-11_25_55]      Epoch: 37       Step: 32600    LastLoss: 0.0006410101777873933                                                                                                      AvgLoss: 0.0008731031231582164   Lr: 0.0072379772059249555
2022-07-28 11:25:57.213 | INFO     | utils.train:start:108 - [2022-07-28-11_25_57]      Epoch: 37       Step: 32700    LastLoss: 0.0009320578537881374                                                                                                      AvgLoss: 0.0008294750811182894   Lr: 0.0072379772059249555
2022-07-28 11:25:59.322 | INFO     | utils.train:start:108 - [2022-07-28-11_25_59]      Epoch: 37       Step: 32800    LastLoss: 0.0009776148945093155                                                                                                      AvgLoss: 0.000850687074707821    Lr: 0.0072379772059249555
2022-07-28 11:26:01.465 | INFO     | utils.train:start:108 - [2022-07-28-11_26_01]      Epoch: 37       Step: 32900    LastLoss: 0.0013811136595904827                                                                                                      AvgLoss: 0.0008380734102684073   Lr: 0.0072379772059249555
2022-07-28 11:26:03.674 | INFO     | utils.train:start:137 - [2022-07-28-11_26_03]      Epoch: 37       Step: 33000    LastLoss: 0.000778629386331886                                                                                                       AvgLoss: 0.000821824642480351    Lr: 0.0072379772059249555       Acc: 0.90625
2022-07-28 11:26:05.869 | INFO     | utils.train:start:108 - [2022-07-28-11_26_05]      Epoch: 37       Step: 33100    LastLoss: 0.000949505774769932                                                                                                       AvgLoss: 0.0008630690455902368   Lr: 0.0072379772059249555
2022-07-28 11:26:08.024 | INFO     | utils.train:start:108 - [2022-07-28-11_26_08]      Epoch: 37       Step: 33200    LastLoss: 0.0009300833917222917                                                                                                      AvgLoss: 0.0008534722673357464   Lr: 0.0072379772059249555
2022-07-28 11:26:10.182 | INFO     | utils.train:start:108 - [2022-07-28-11_26_10]      Epoch: 37       Step: 33300    LastLoss: 0.0007823986816219985                                                                                                      AvgLoss: 0.0008065305658965372   Lr: 0.0072379772059249555
2022-07-28 11:26:12.454 | INFO     | utils.train:start:108 - [2022-07-28-11_26_12]      Epoch: 37       Step: 33400    LastLoss: 0.0007098791538737714                                                                                                      AvgLoss: 0.0008171254771878011   Lr: 0.0072379772059249555
2022-07-28 11:26:14.961 | INFO     | utils.train:start:108 - [2022-07-28-11_26_14]      Epoch: 38       Step: 33500    LastLoss: 0.001108370954170823                                                                                                       AvgLoss: 0.0008040564699331299   Lr: 0.0072379772059249555
2022-07-28 11:26:17.309 | INFO     | utils.train:start:108 - [2022-07-28-11_26_17]      Epoch: 38       Step: 33600    LastLoss: 0.0012630750425159931                                                                                                      AvgLoss: 0.0007878648146288469   Lr: 0.0072379772059249555
2022-07-28 11:26:20.348 | INFO     | utils.train:start:108 - [2022-07-28-11_26_20]      Epoch: 38       Step: 33700    LastLoss: 0.0008831340819597244                                                                                                      AvgLoss: 0.0007882761370274238   Lr: 0.0072379772059249555
2022-07-28 11:26:24.197 | INFO     | utils.train:start:108 - [2022-07-28-11_26_24]      Epoch: 38       Step: 33800    LastLoss: 0.0005721147754229605                                                                                                      AvgLoss: 0.0008209841320058331   Lr: 0.0072379772059249555
2022-07-28 11:26:28.109 | INFO     | utils.train:start:108 - [2022-07-28-11_26_28]      Epoch: 38       Step: 33900    LastLoss: 0.0007059407653287053                                                                                                      AvgLoss: 0.0008052434003911912   Lr: 0.0072379772059249555
2022-07-28 11:26:32.127 | INFO     | utils.train:start:137 - [2022-07-28-11_26_32]      Epoch: 38       Step: 34000    LastLoss: 0.0009513929835520685                                                                                                      AvgLoss: 0.0008047035793424584   Lr: 0.0072379772059249555       Acc: 1.0
2022-07-28 11:26:32.142 | INFO     | utils.train:start:143 -
Training Finished!Exporting Model...
Traceback (most recent call last):
  File "app.py", line 33, in <module>
    fire.Fire(App)
  File "C:\Users\yxn\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\yxn\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\yxn\AppData\Local\Programs\Python\Python38\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "app.py", line 28, in train
    trainer.start()
  File "D:\works\dddd_trainer\utils\train.py", line 152, in start
    self.net.export_onnx(self.net, dummy_input,
  File "D:\works\dddd_trainer\nets\__init__.py", line 216, in export_onnx
    torch.onnx.export(net, dummy_input, graph_path, export_params=True, verbose=False,
TypeError: export() got an unexpected keyword argument '_retain_param_name'

**训练完遇到了同样的问题，数据集我用的captcha库生成的4位验证码，大概有2.8w张，前后运行了两次，均提示上述错误，求大佬指导下。。。**

**Comment by sml2h3** [comment]
直接删掉 _retain_param_name
