### ISSUE TITLE
这个报错是啥意思

### ISSUE THREAD

**Issue by amd5** [sml2h3/dddd_trainer#35]
```
2023-07-26 04:37:11.717 | INFO     | utils.train:start:110 - [2023-07-26-04_37_11]	Epoch: 35952	Step: 1725700	LastLoss: 0.00010419684986118227	AvgLoss: 0.00012866455923358445	Lr: 2.7344957135266526e-10
2023-07-26 04:37:14.401 | INFO     | utils.train:start:110 - [2023-07-26-04_37_14]	Epoch: 35954	Step: 1725800	LastLoss: 0.00011213675315957516	AvgLoss: 0.00012821589938539547	Lr: 2.7344957135266526e-10
2023-07-26 04:37:17.084 | INFO     | utils.train:start:110 - [2023-07-26-04_37_17]	Epoch: 35956	Step: 1725900	LastLoss: 0.00011715076107066125	AvgLoss: 0.00012866744575148914	Lr: 2.7344957135266526e-10
Traceback (most recent call last):
  File "/www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/torch/serialization.py", line 499, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/www/wwwroot/dddd_trainer/app.py", line 33, in <module>
    fire.Fire(App)
  File "/www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/fire/core.py", line 480, in _Fire
    target=component.__name__)
  File "/www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/www/wwwroot/dddd_trainer/app.py", line 28, in train
    trainer.start()
  File "/www/wwwroot/dddd_trainer/utils/train.py", line 120, in start
    "epoch": self.epoch, "step": self.step, "lr": lr})
  File "/www/wwwroot/dddd_trainer/nets/__init__.py", line 188, in save_model
    torch.save(net, path)
  File "/www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/torch/serialization.py", line 380, in save
    return
  File "/www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/torch/serialization.py", line 259, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:300] . unexpected pos 17094848 vs 17094736
terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at inline_container.cc:300] . unexpected pos 17094848 vs 17094736
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x47 (0x7fe49ddc3ae7 in /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2797840 (0x7fe4e3e5c840 in /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x2792e1c (0x7fe4e3e57e1c in /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #3: caffe2::serialize::PyTorchStreamWriter::writeRecord(std::string const&, void const*, unsigned long, bool) + 0xb5 (0x7fe4e3e5fa85 in /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #4: caffe2::serialize::PyTorchStreamWriter::writeEndOfFile() + 0x173 (0x7fe4e3e5fd73 in /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #5: caffe2::serialize::PyTorchStreamWriter::~PyTorchStreamWriter() + 0x125 (0x7fe4e3e5ffe5 in /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0xb43ee3 (0x7fe56504eee3 in /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x2a73f8 (0x7fe5647b23f8 in /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x2a86fe (0x7fe5647b36fe in /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #9: /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3() [0x480622]
frame #10: /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3() [0x434697]
frame #11: /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3() [0x4346a7]
frame #12: /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3() [0x4346a7]
frame #13: /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3() [0x4346a7]
frame #14: /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3() [0x4346a7]
frame #15: /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3() [0x4346a7]
frame #16: /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3() [0x4346a7]
frame #17: /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3() [0x4346a7]
frame #18: PyDict_SetItemString + 0x3b7 (0x4a2647 in /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3)
frame #19: PyImport_Cleanup + 0x71 (0x565771 in /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3)
frame #20: /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3() [0x421d98]
frame #21: Py_Main + 0x640 (0x43b7d0 in /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3)
frame #22: main + 0x162 (0x41d982 in /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3)
frame #23: __libc_start_main + 0xf5 (0x7fe57390c555 in /lib64/libc.so.6)
frame #24: /www/wwwroot/dddd_trainer/11ddbaf3386aea1f2974eee984542152_venv/bin/python3() [0x41da40]

已放弃
[root@RTX3090 dddd_trainer]# 

```

**Comment by amd5** [comment]
```
OSError: [Errno 28] No space left on device
磁盘空间不足.......................
```
