### ISSUE TITLE
StopIteration 問題

### ISSUE THREAD

**Issue by Tspm1eca** [sml2h3/dddd_trainer#46]
只要加入某張圖片就會出現StopIteration，但我完全不知道這圖片有什麼問題，都是用同樣的手法採集的。
![0+1_56165942e06a39fbe0fe6034524cc773ba9f59fe](https://github.com/sml2h3/dddd_trainer/assets/34676937/73d8189d-9cc0-4241-967d-a1298da43fe7)
：
```
Traceback (most recent call last):
  File "E:\Daz3D Workshop\Enhance_Queue\_dddd_trainer\utils\train.py", line 124, in start
    test_inputs, test_labels, test_labels_length = next(val_iter)
  File "C:\Users\T1me\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\T1me\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 560, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "C:\Users\T1me\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Daz3D Workshop\Enhance_Queue\_dddd_trainer\app.py", line 33, in <module>
    fire.Fire(App)
  File "C:\Users\T1me\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\T1me\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\T1me\AppData\Local\Programs\Python\Python39\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "E:\Daz3D Workshop\Enhance_Queue\_dddd_trainer\app.py", line 28, in train
    trainer.start()
  File "E:\Daz3D Workshop\Enhance_Queue\_dddd_trainer\utils\train.py", line 128, in start
    test_inputs, test_labels, test_labels_length = next(val_iter)
  File "C:\Users\T1me\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\T1me\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 560, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "C:\Users\T1me\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
StopIteration
```

**Comment by DokiDoki1103** [comment]
我也遇到这个问题了
